const data = [
    {
      id: 1,
      href:'page1.html',
      img:'./img/quran.jpg',
      title: 'কালেমা',
      description: 'পাঁচ কালেমা বাংলা অর্থসহ',
    },
    {
      id: 2,
      href:'./pages/namaj.html',
      img:'./img/quran.jpg',
      title: 'নামাজ',
      description: 'সকল নামাজের বিবরণ',
    },
    {
        id: 3,
        href:'./pages/roja.html',
        img:'./img/quran.jpg',
        title: 'রোজা',
        description: 'সকল প্রকার রোজার বিবরণ',
      },
    {
        id: 4,
        href:'./pages/haj.html',
        img:'./img/quran.jpg',
        title: 'হজ্জ',
        description: 'হজ্জ ও ওমরাহ্ বিবরণ',
    },
    {
        id: 5,
        href:'./pages/jakat.html',
        img:'./img/quran.jpg',
        title: 'যাকাত',
        description: 'যাকাত ও সদকা আদায়ের নিয়ম',
    },
    {
        id: 6,
        href:'./pages/azan.html',
        img:'./img/quran.jpg',
        title: 'আযান ও ইকামা',
        description: 'যাকাত ও সদকা আদায়ের নিয়ম',
    },
    {
        id: 7,
        href:'./pages/pobitrota.html',
        img:'./img/quran.jpg',
        title: 'পবিত্রতা',
        description: 'যাকাত ও সদকা আদায়ের নিয়ম',
    },
    {
        id: 8,
        href:'./pages/nafalnamaj.html',
        img:'./img/quran.jpg',
        title: 'গুরুত্বপূর্ণ নফল নামাজ',
        description: 'গুরুত্বপূর্ণ নফল নামাজ আদায়ের নিয়ম',
    },
    {
        id: 9,
        href:'./pages/kajanamaj.html',
        img:'./img/quran.jpg',
        title: 'কাযা নামাজের নিয়ম',
        description: 'কাযা পড়ার নিয়ম',
    },
    {
        id: 10,
        href:'./pages/eid.html',
        img:'./img/quran.jpg',
        title: 'ঈদ',
        description: 'ঈদ ও ঈদের নামাজের নিয়ম',
    },
    {
        id: 11,
        href:'./pages/qurbani.html',
        img:'./img/quran.jpg',
        title: 'কুরবানি ও আকিকা',
        description: 'কুরবানি ও আকিকা করার নিয়ম',
    },
    {
        id: 12,
        href:'./list-quran.html',
        img:'./img/quran.jpg',
        title: 'নামাজের প্রয়োজনীয় সূরা',
        description: 'দরকারী কিছু ছোট সূরা',
    },
    {
        id: 13,
        href:'./pages/hadis.html',
        img:'./img/quran.jpg',
        title: '',
        description: '',
    },
    {
        id: 14,
        href:'./pages/hadis.html',
        img:'./img/quran.jpg',
        title: 'হাদিস',
        description: 'প্রয়োজনীয় কিছু হাদিস',
    },
    {
        id: 15,
        href:'./pages/dowa.html',
        img:'./img/quran.jpg',
        title: 'দোয়া দরুদ',
        description: 'প্রয়োজনীয় দোয়া দরুদ সমূহ',
    },
    {
        id: 16,
        href:'./99th-name.html',
        img:'./img/quran.jpg',
        title: 'আল্লাহর ৯৯ নাম',
        description: 'আল্লাহর ৯৯ নাম ও ফজিলত ',
    },
    {
        id: 17,
        href:'./pages/akaied.html',
        img:'./img/quran.jpg',
        title: 'আকাইদ ও নৈতিক জীবন',
        description: 'ইসলামিক জীবন বিধান',
    },
    {
        id: 18,
        href:'./pages/akhlak.html',
        img:'./img/quran.jpg',
        title: 'আখলাক বা চরিত্র',
        description: 'চরিত্র গঠন',
    },
    {
        id: 19,
        href:'./pages/kabar.html',
        img:'./img/quran.jpg',
        title: 'কবর জিয়ারত',
        description: 'কবর জিয়ারত করার নিয়ম',
    },
    {
        id: 20,
        href:'./pages/amal.html',
        img:'./img/quran.jpg',
        title: 'আমল ও সায়্যিদুল ইস্তেগফার',
        description: 'আমল ও সায়্যিদুল ইস্তেগফার',
    },
  ];
  