const openpage = [
    {
      id: 1,
      href:'page1.html',
      img:'./img/quran.jpg',
      title: 'কালেমা',
      description: 'পাঁচ কালেমা বাংলা অর্থসহ',
    },
    {
      id: 2,
      href:'./pages/namaj.html',
      img:'./img/quran.jpg',
      title: 'নামাজ',
      description: 'সকল নামাজের বিবরণ',
    },
    {
        id: 3,
        href:'./pages/roja.html',
        img:'./img/quran.jpg',
        title: 'রোজা',
        description: 'সকল প্রকার রোজার বিবরণ',
      },
    {
        id: 4,
        href:'./pages/haj.html',
        img:'./img/quran.jpg',
        title: 'হজ্জ',
        description: 'হজ্জ ও ওমরাহ্ বিবরণ',
    },
    {
        id: 5,
        href:'./pages/jakat.html',
        img:'./img/quran.jpg',
        title: 'যাকাত',
        description: 'যাকাত ও সদকা আদায়ের নিয়ম',
    },
    {
        id: 6,
        href:'./pages/azan.html',
        img:'./img/quran.jpg',
        title: 'আযান ও ইকামা',
        description: 'যাকাত ও সদকা আদায়ের নিয়ম',
    },
    {
        id: 7,
        href:'./pages/pobitrota.html',
        img:'./img/quran.jpg',
        title: 'পবিত্রতা',
        description: 'যাকাত ও সদকা আদায়ের নিয়ম',
    },
    {
        id: 8,
        href:'./pages/nafalnamaj.html',
        img:'./img/quran.jpg',
        title: 'গুরুত্বপূর্ণ নফল নামাজ',
        description: 'গুরুত্বপূর্ণ নফল নামাজ আদায়ের নিয়ম',
    },
    {
        id: 9,
        href:'./pages/kajanamaj.html',
        img:'./img/quran.jpg',
        title: 'কাযা নামাজের নিয়ম',
        description: 'কাযা পড়ার নিয়ম',
    },
    {
        id: 10,
        href:'./pages/eid.html',
        img:'./img/quran.jpg',
        title: 'ঈদ',
        description: 'ঈদ ও ঈদের নামাজের নিয়ম',
    },
    {
        id: 11,
        href:'./pages/qurbani.html',
        img:'./img/quran.jpg',
        title: 'কুরবানি ও আকিকা',
        description: 'কুরবানি ও আকিকা করার নিয়ম',
    },
    {
        id: 12,
        href:'./list-quran.html',
        img:'./img/quran.jpg',
        title: 'নামাজের প্রয়োজনীয় সূরা',
        description: 'দরকারী কিছু ছোট সূরা',
    },
    {
        id: 14,
        href:'./pages/hadis.html',
        img:'./img/quran.jpg',
        title: 'হাদিস',
        description: 'প্রয়োজনীয় কিছু হাদিস',
    },
    {
        id: 15,
        href:'./pages/dowa.html',
        img:'./img/quran.jpg',
        title: 'দোয়া দরুদ',
        description: 'প্রয়োজনীয় দোয়া দরুদ সমূহ',
    },
    {
        id: 16,
        href:'./99th-name.html',
        img:'./img/quran.jpg',
        title: 'আল্লাহর ৯৯ নাম',
        description: 'আল্লাহর ৯৯ নাম ও ফজিলত ',
    },
    {
        id: 17,
        href:'./pages/akaied.html',
        img:'./img/quran.jpg',
        title: 'আকাইদ ও নৈতিক জীবন',
        description: 'ইসলামিক জীবন বিধান',
    },
    {
        id: 18,
        href:'./pages/akhlak.html',
        img:'./img/quran.jpg',
        title: 'আখলাক বা চরিত্র',
        description: 'চরিত্র গঠন',
    },
    {
        id: 19,
        href:'./pages/kabar.html',
        img:'./img/quran.jpg',
        title: 'কবর জিয়ারত',
        description: 'কবর জিয়ারত করার নিয়ম',
    },
    {
        id: 20,
        href:'./pages/amal.html',
        img:'./img/quran.jpg',
        title: 'আমল ও সায়্যিদুল ইস্তেগফার',
        description: 'আমল ও সায়্যিদুল ইস্তেগফার',
    },
    {
        id: 21,
        href:'./pages/amal-2.html',
        img:'./img/quran.jpg',
        title: 'বিভিন্ন আয়াতের আমল ও ফজীলত',
        description: 'ছোাট আমল ও ফজীলত',
    },
    {
        id: 22,
        href:'./pages/dafon-kafon.html',
        img:'./img/quran.jpg',
        title: 'কাফন-দাফন',
        description: 'কাফন-দাফন করার নিয়ম',
    },
    {
        id: 23,
        href:'./pages/kobore-qustin.html',
        img:'./img/quran.jpg',
        title: 'কবরে প্রশ্ন ও শান্তি',
        description: 'কবরে প্রশ্ন ও শান্তি',
    },
    {
        id: 24,
        href:'counter.html',
        img:'./img/quran.jpg',
        title: 'তাসবিহ',
        description: 'তাসবিহ পড়ুন এখান থেকে',
    },
    {
        id: 25,
        href:'./islamic-name/index.html',
        img:'./img/quran.jpg',
        title: 'ইসলামিক নাম',
        description: 'ছেলে ও মেয়েদের জন্য ইসলামিক নাম',
    },
    {
        id: 26,
        href:'https://qiblafinder.withgoogle.com/intl/en/finder/ar',
        img:'./img/quran.jpg',
        title: 'কাবা (কম্পাস)',
        description: 'কেবলার দিক নির্ণয়....',
    },
    {
        id: 27,
        href:'./pages/eid-e-meladunnabi.html',
        img:'./img/quran.jpg',
        title: 'ঈদ-ই-মিলাদুন্নবী',
        description: 'ঈদ-ই-মিলাদুন্নবী বর্নণা',
    },
    {
        id: 28,
        href:'./pages/islami-ukti.html',
        img:'./img/quran.jpg',
        title: 'ইসলামিক উক্তি',
        description: 'ছোট ইসলামিক উক্তি হাদিস',
    },
    {
        id: 29,
        href:'./pages/al-quran.html',
        img:'./img/quran.jpg',
        title: 'পবিত্র কুরআন',
        description: 'পবিত্র কুরআন',
    },
    {
        id: 30,
        href:'./pages/alquran-fajilot.html',
        img:'./img/quran.jpg',
        title: 'পবিত্র কুরআনের ফর্যীলত',
        description: 'পবিত্র কুরআনের ফর্যীলত',
    },
    {
        id: 31,
        href:'./pages/adio-full-quran.html',
        img:'./img/quran.jpg',
        title: 'সম্পূর্ণ কুরআন অডিও',
        description: 'সম্পূর্ণ কুরআন অডিও',
    },
    {
        id: 32,
        href:'./pages/islami-vedios.html',
        img:'./img/quran.jpg',
        title: 'ইসলামি শিক্ষনীয় ভিডিও',
        description: 'ইসলামি শিক্ষনীয় ভিডিও',
    },
    {
        id: 33,
        href:'./pages/nabiger-jiboni.html',
        img:'./img/quran.jpg',
        title: 'হযরত মুহাম্মদ (সাঃ) এর জীবনী সংক্ষেপে',
        description: 'হযরত মুহাম্মদ (সাঃ) এর জীবনী সংক্ষেপে',
    },
    {
        id: 34,
        href:'./pages/kholafayea-rashedin.html',
        img:'./img/quran.jpg',
        title: 'খোলাফায়ে রাশেদিনের জীবনাদর্শ',
        description: 'খোলাফায়ে রাশেদিনের জীবনাদর্শ',
    },

    {
        id: 35,
        href:'./pdf/index.html',
        img:'./img/quran.jpg',
        title: 'সম্পূর্ণ কোরআন',
        description: 'হিফজুল কোরআন',
    },
    {
        id: 36,
        href:'./calender/index.html',
        img:'./img/quran.jpg',
        title: 'ক্যালেন্ডার',
        description: 'ক্যালেন্ডার আরবী বাংলা ইংরেজী',
    },
  ];
  